recipe-tracker:
  build: .
  environment:
    EVENTSTORE_URL: "http://eventstore:2113/"
    HOST: "0.0.0.0"
    PORT: 3000
  ports:
    - "3000:3000"
  links:
    - eventstore

eventstore:
  image: eventstore/eventstore
  environment:
    EVENTSTORE_RUN_PROJECTIONS: All
    EVENTSTORE_DB: "/var/db"
  volumes:
    - "./db:/var/db"
  ports:
    - "2113:2113"
    - "1113:1113"
